@startuml
'https://plantuml.com/class-diagram

@startuml
class Persona {
    -nombre: String
    -edad: int
    +getNombre(): String
    +setNombre(nuevoNombre: String): void
    +getEdad(): int
    +setEdad(nuevaEdad: int): void
}

@enduml