@startuml
'https://plantuml.com/class-diagram

class Contacto {
  - nombre: String
  - telefono: String
  - correo: String
  + etiquetas: Etiqueta[]
  +agregarEtiqueta(etiqueta: Etiqueta): void
  +eliminarEtiqueta(etiqueta: Etiqueta): void
}

class Agenda {
  - contactos: Contacto[]
  + agregarContacto(contacto: Contacto)
  + eliminarContacto(contacto: Contacto)
  + buscarContacto(nombre: String): Contacto
}

class Etiqueta {
  - nombre: String
}

' --- Relaciones ---
Contacto "1" -- "*" Etiqueta : tiene
Agenda "1" -- "*" Contacto : gestiona

@enduml