@startuml
'https://plantuml.com/class-diagram

abstract class Usuario {
  - nombre: String
  - email: String
  - fechaRegistro: Date
  - seguidores: usuario: Usuario[]
  - seguidos: usuario: Usuario[]
  + publicar(contenido: String): Publicacion
  + comentar(publicacion: Publicacion, texto: String): Comentario
  + seguirUsuario(usuario: Usuario): void
  + unirseAGrupo(grupo: Grupo): void
  + verPerfil(): void
}

class Estudiante extends Usuario {
  - grupo: String
  + carrera: String
}

class Docente extends Usuario {
  - asignatura: String
}

class Egresado extends Usuario {
  - especialidad: String
  - anioEgreso: int
}

class Publicacion {
  - id: String
  - contenido: String
  - fecha: Date
  - autor: Usuario
  + agregarComentario(comentario: Comentario): void
  + obtenerComentarios(): Comentario[]
}

class Comentario {
  - id: String
  - texto: String
  - fechaComentario: Date
  - autor: Usuario
}

class Grupo {
  - id: String
  - nombre: String
  - descripcion: String
  - fechaCreacion: Date
  - miembros: usuario[]
  + agregarMiembro(usuario: Usuario): void
  + eliminarMiembro(usuario: Usuario): void
 }

' ' --- Relaciones ---
Usuario "1" -- "*" Publicacion : crea
Usuario "1" -- "*" Comentario : escribe
Usuario "0..*" -- "0..*" Usuario : sigue

Publicacion "1" -- "*" Comentario : tiene
Publicacion "1" -- "1" Usuario : publicada por

Comentario "1" -- "1" Usuario : comentado por

Usuario "0..*" -- "*" Grupo : participa en
Grupo "1" -- "0..*" Usuario : tiene como miembros
Grupo "0..*" -- "0..*" Publicacion : contiene

@enduml