@startuml
'https://plantuml.com/class-diagram

class Cuenta {
    - numero: String
    - titular: String
    - saldo: double
    + getSaldo(): float
    + getTitular(): String
    + getNumero(): String
    + depositar(monto: double): void
    + retirar(monto: double): void
}

@enduml