@startuml
'https://plantuml.com/class-diagram

class Paciente {
  - id: String
  - ci: String
  - nombre: String
  +solicitarTurno(medico: Medico, fecha: Date): Turno
}

class Medico {
  - nombre: String
  - matricula: String
  + atender(turno: Turno): void
}

class Turno {
  - fecha: Date
  - hora: Time
  - estado: String
}

class Historial {
  - registros: RegistroMedico[]
  + agregarRegistro(registro: RegistroMedico): void
}

class Cirujano extends Medico {
  + realizarOperacion(): void
}

class Clinico extends Medico {
  + realizarConsulta(): void
}

class Area {
  - codigo: String
  - nombre: String
}

class RegistroMedico{
    - fecha: Date
    - descripcion: String
    + getRegistro(): String
}

' --- Relaciones ---
Paciente "1" -- "1" Historial: tiene
Paciente "1" -- "*" Turno: tiene
Medico "1" -- "*" Turno: atiende
Medico "1" -- "*" Area: pertenece
Medico "1" -- "*" RegistroMedico: realiza
Historial "1" -- "*" RegistroMedico: contiene


@enduml